hyperledger-iroha/iroha-javascript

- src/index.js
- src/iroha.js
@MizukiSonoko 
@takemiyamakoto
> Fix license

- README.md
- src/iroha.js
I change function name from createSignature to sign.
> Fix functionName from  createSignature to sign

- packages/iroha-client/package.json
Forgot to do it in previous PR (
> Bump `@iroha2/client` version to 0.2.0

- etc/report/data-model.api.md
- packages/client/src/client.ts
- packages/data-model/input/input.json
- packages/data-model/src/generated.ts
- Update data model
- Fix query entrypoint at client
> Update schema & fix querying

- package.json
- src/util.ts
Signed-off-by: Stefan Popov <stefanpopov@list.ru>
> Bump version

- README.md
Signed-off-by: Sara <lira.lemur@gmail.com>
Fixed a badge in README
> Fix: README Badge

- etc/meta.ts
- etc/scripts/api-extractor.ts
- etc/scripts/bundle.ts
> misc: update scripts so `data-model-schema` package should be published

- .npmrc
Signed-off-by: 0x009922 <a.marcius26@gmail.com>
> [ci]: set `publish-branch` to `iroha2`

- .changeset/lemon-knives-exist.md
- packages/client/src/client.ts
- packages/client/src/collect-garbage.ts
Signed-off-by: 0x009922 <a.marcius26@gmail.com>
Closes #113
> [feat] #113: expose new client methods

- packages/client/README.md
- packages/client/test/integration/config/peer_config.json
- packages/client/test/integration/test-node/multiple.spec.ts
- packages/data-model-rust-samples/Cargo.lock
- packages/data-model-rust-samples/Cargo.toml
- packages/data-model/README.md
- packages/dev-iroha-bins/src/config.ts
- packages/test-peer/src/lib.ts
- packages/test-peer/src/util.ts
Signed-off-by: 0x009922 <a.marcius26@gmail.com>
Closes #129
> [test]: enable block-streaming test back

- Jenkinsfile
Signed-off-by: BAStos525 <jungle.vas@yandex.ru>
Duty/21-12-22: Move jake checks stage
Run `pnpm jake run-all-checks` command on test stage optional for PR and do not run it on
> Duty/21-12-22: Make jake checks stage optional

- Jenkinsfile
- package.json
[DOPS-2312] Create images with corepack
1. Update pipeline
Signed-off-by: name <zaporozhets@soramitsu.co.jp>
[DOPS-2312]: https://soramitsu.atlassian.net/browse/DOPS-2312
> [DOPS: 2312] Create images with corepack 

- README.md
Small convenience-related change: add links
> README: add links

- packages/iroha-source/config.js
- pnpm-lock.yaml
Forgot to do as part of #202 (CI didn't work...)
> Fix lockfile

- .github/workflows/pull-request.yml
- crypto-wasm/Cargo.lock
- crypto-wasm/Cargo.toml
> chore: switch to `hyperledger-iroha` (#208)

- deno.jsonc
- packages/core/deno.jsonc
> chore(core, client): exclude extra files from publishing #211

- packages/client/query.ts
> fix: make `deno publish` work, close #238

- README.md
- Releases.md
- packages/core/crypto/mod.ts
- packages/core/deno.jsonc
- packages/core/mod.ts
Signed-off-by: 0x009922 <43530070+0x009922@users.noreply.github.com>
> docs(core): update compatibility info

- .github/workflows/pull-request.yml
- packages/core/tests/misc.test.ts
- tests/node/tests/client-apis.spec.ts
And support `v2.0.0-rc.2.0` as a whole.
> feat(core, client): include `commitTime` into `Status`

- packages/client-web-socket-node/mod.ts
- packages/client/mod.ts
- packages/client/web-socket/native.ts
> docs(client, client-web-socket-node): extend web socket support docs
